package com.zwolsman.ptcgl.mirror

import com.zwolsman.ptcgl.mirror.rainier.codec.DataTableCodec
import com.zwolsman.ptcgl.mirror.rainier.codec.DotNetBinaryReader
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.assertTrue

/**
 * Compares the sv1/FR and sv1/EN card DB fixtures to validate multi-locale assumptions.
 *
 * Fixtures are generated by VerifyCardDbRunner (--verify-card-db flag). Both locale
 * fixtures must be present; the test is silently skipped when either is absent.
 *
 *   src/test/resources/fixtures/card-db-sv1-en.bin
 *   src/test/resources/fixtures/card-db-sv1-fr.bin
 */
class FrCardDbVerifyTest {

    private val fixtureBinEn = Path.of("src/test/resources/fixtures/card-db-sv1-en.bin")
    private val fixtureBinFr = Path.of("src/test/resources/fixtures/card-db-sv1-fr.bin")

    @Test
    fun `FR and EN fixtures have the same row count`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)
        assertTrue(en.rows.isNotEmpty(), "EN table must have rows")
        assertTrue(en.rows.size == fr.rows.size,
            "Row count mismatch: EN=${en.rows.size} FR=${fr.rows.size}")
    }

    @Test
    fun `FR has more columns than EN (locale-prefixed attack columns)`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)

        val enCols = en.columns.map { it.name }.toSet()
        val frCols = fr.columns.map { it.name }.toSet()
        val onlyInFr = frCols - enCols

        println("EN columns: ${en.columns.size}, FR columns: ${fr.columns.size}")
        println("Only in FR: $onlyInFr")

        assertTrue(fr.columns.size > en.columns.size,
            "FR DataTable should have more columns than EN (locale-prefixed attack columns)")
        assertTrue(onlyInFr.contains("FR Attack Name"),
            "Expected 'FR Attack Name' column in FR table. Only-in-FR: $onlyInFr")
        assertTrue(onlyInFr.contains("FR Attack Text"),
            "Expected 'FR Attack Text' column in FR table. Only-in-FR: $onlyInFr")
        assertTrue(onlyInFr.contains("FR Card Name"),
            "Expected 'FR Card Name' column in FR table. Only-in-FR: $onlyInFr")
    }

    @Test
    fun `EN columns are a strict subset of FR columns`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)

        val enCols = en.columns.map { it.name }.toSet()
        val frCols = fr.columns.map { it.name }.toSet()
        val onlyInEn = enCols - frCols

        assertTrue(onlyInEn.isEmpty(),
            "All EN columns should be present in FR table. Missing from FR: $onlyInEn")
    }

    @Test
    fun `LocalizedCardName is locale-specific in both fixtures`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)

        val enRow = en.rows.first()
        val cardId = enRow["cardID"]
        val frRow = fr.rows.first { it["cardID"] == cardId }

        val enName = enRow["LocalizedCardName"]?.toString()
        val frName = frRow["LocalizedCardName"]?.toString()

        println("EN LocalizedCardName: $enName")
        println("FR LocalizedCardName: $frName")

        assertTrue(enName != null && enName.isNotBlank(), "EN LocalizedCardName must be present")
        assertTrue(frName != null && frName.isNotBlank(), "FR LocalizedCardName must be present")
        assertTrue(enName != frName,
            "LocalizedCardName should differ between locales for card $cardId: EN=$enName, FR=$frName")
    }

    @Test
    fun `FR attack names differ from EN attack names`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)

        // Find a card that has an attack in both tables
        val enRowWithAttack = en.rows.first { row ->
            row["EN Attack Name"]?.toString()?.isNotBlank() == true
        }
        val cardId = enRowWithAttack["cardID"]
        val frRow = fr.rows.first { it["cardID"] == cardId }

        val enAttackName = enRowWithAttack["EN Attack Name"]?.toString()
        val frAttackName = frRow["FR Attack Name"]?.toString()

        println("Card: $cardId")
        println("EN Attack Name (EN column): $enAttackName")
        println("FR Attack Name (FR column): $frAttackName")

        assertTrue(frAttackName != null && frAttackName.isNotBlank(),
            "FR Attack Name column must be present and non-blank in FR table for card $cardId")
        assertTrue(enAttackName != frAttackName,
            "FR attack name should differ from EN attack name for card $cardId")
    }

    @Test
    fun `locale-invariant fields are identical between EN and FR`() {
        if (Files.notExists(fixtureBinEn) || Files.notExists(fixtureBinFr)) return
        val en = parse(fixtureBinEn)
        val fr = parse(fixtureBinFr)

        val invariantCols = listOf(
            "HP", "Retreat", "Damage", "EN Cost",
            "EN Weakness Type", "Weakness Amount",
            "EN Type", "Regulations symbol",
            "Loc Rarity Code", "CompSea Card Number",
            "category", "archetypeID",
        )

        val mismatches = mutableListOf<String>()
        for (enRow in en.rows) {
            val cardId = enRow["cardID"] ?: continue
            val frRow = fr.rows.firstOrNull { it["cardID"] == cardId } ?: continue
            for (col in invariantCols) {
                if (enRow[col] != frRow[col]) {
                    mismatches += "card=$cardId col=$col EN=${enRow[col]} FR=${frRow[col]}"
                }
            }
        }

        assertTrue(mismatches.isEmpty(),
            "Locale-invariant fields must be identical between EN and FR. Mismatches:\n${mismatches.joinToString("\n")}")
    }

    private fun parse(path: Path): DataTableCodec.Table =
        DataTableCodec.parse(DotNetBinaryReader(Files.readAllBytes(path)))
}
