apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ptcgl-mirror
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mirror=ghcr.io/zwolsman/ptcgl-mirror
    argocd-image-updater.argoproj.io/mirror.update-strategy: digest
    argocd-image-updater.argoproj.io/mirror.tag-override: latest
spec:
  project: default
  source:
    repoURL: https://github.com/zwolsman/ptcgl-mirror
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
