apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptcgl-web
  namespace: ptcgl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptcgl-web
  template:
    metadata:
      labels:
        app: ptcgl-web
    spec:
      containers:
        - name: web
          image: ghcr.io/zwolsman/ptcgl-web:latest
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
