apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: ptcgl
type: Opaque
stringData:
  # Must match postgres-credentials
  SPRING_DATASOURCE_USERNAME: ptcgl
  SPRING_DATASOURCE_PASSWORD: changeme
