spring:
  autoconfigure:
    exclude: []
  datasource:
    url: jdbc:postgresql://localhost:5432/ptcgl
    username: ptcgl
    password: ptcgl
  flyway:
    enabled: true

mirror:
  s3:
    endpoint: http://localhost:9000
    access-key: rustfsadmin
    secret-key: rustfsadmin
    bucket: ptcgl-dev
    region: us-east-1
    force-path-style: true
